[workspace]
members = [
    "crates/ingest",
    "crates/koz",
    "crates/koz-storage",
    "crates/swain",
]

resolver = "2"

[profile.dev.package."*"]
opt-level = 3
debug = "line-tables-only"
debug-assertions = true
